### ISSUE TITLE
Uniform format for signup

### ISSUE THREAD

**Issue by vaswal** [khanayazahmad/CMPE-273-Group-Project-Twitter#1]
Currently, successful sign-up produces the following output. Is it possible to use the same output format when handling an unsuccessful signup? For example, in the case of duplicate signup details,  the output is a plain text message - "EMAIL OR USERNAME ALREADY EXITS".

```
{
    "status": "ok",
    "data": {
        "message": "USER SUCCESSFULLY REGISTERED"
    }
}
```

**Comment by Vijay2502** [comment]
updated response format.
